fix(stuck-detector): Use metrics directly (#517)
Fixing this issue with the metrics buffer, which was designed to only
deal with one thread:

```
Traceback (most recent call last):
  File "threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
  File "threading.py", line 1041, in _bootstrap_inner
    self.run()
  File "threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
  File "arroyo/processing/processor.py", line 402, in f
    self.__metrics_buffer.flush()
  File "arroyo/processing/processor.py", line 131, in flush
    for metric, value in self.__timers.items():
RuntimeError: dictionary changed size during iteration
```